subtask: "openproblems_bmmc_cite_phase2_rna"
batch_size: 520
act: "leaky_relu"
conv_flow: ['gat']
agg_flow: [null]
device: "cpu"
learning_rate: 0.00004
hidden_size: 512
num_heads: 2
n_neigbours: 3
n_components: 1200
metric: "nan_euclidean"
dropout_rate: 0.2
num_epochs: 500
seed: 1
es_patience: 50
es_min_delta: 0.01
es_rate_threshold: 0.0008
layer_dim_ex: 3
verbose: true
sample: true
preprocessing_type: "SVD"
